=== Ron-ZL/verifaps-lib/src/xsd/exteta-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://formal.iti.kit.edu/exteta-1.0"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:tns="http://formal.iti.kit.edu/exteta-1.0">

	<include schemaLocation=""></include>
	<include schemaLocation=""></include>
	<element name="extended-test-table" type="tns:extendedTestTableType">

	</element>


	<complexType name="extendedTestTableType">
		<sequence>
			<element name="variables" type="tns:variablesType" minOccurs="1"
				maxOccurs="1">
			</element>
			<element name="steps" type="tns:stepsType" minOccurs="1"
				maxOccurs="1">
			</element>
		</sequence>
		<attribute name="version" type="string" use="optional"
			default="1.0"></attribute>
	</complexType>

	<complexType name="variablesType">
		<sequence>
			<element name="variable" type="tns:variableType" minOccurs="0"
				maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="variableType">
		<attribute name="name" type="string"></attribute>
		<attribute name="data-type" type="tns:dataTypeType"></attribute>
		<attribute name="io" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="input"></enumeration>
					<enumeration value="output"></enumeration>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<complexType name="stepsType">
		<sequence>
			<element name="step" type="tns:stepType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="stepType">
		<sequence minOccurs="0" maxOccurs="unbounded">
			<element name="cell" type="string" />
			<!-- <choice> <element name="const" type="tns:cellSimpleValueType" /> 
				<element name="capture" type="string" /> <element name="expr" type="tns:cellExpressionType" 
				/> <element name="dontcare" type="tns:cellDontCareType" /> <element name="rel" 
				type="tns:cellRelationType" /> </choice> -->
		</sequence>
		<attribute name="duration" type="tns:durationType" use="optional"
			default="1"></attribute>


	</complexType>

	<simpleType name="durationType">
		<restriction base="string">
			<pattern value="\d+"></pattern>
			<pattern value="\*"></pattern>
			<pattern value="\[(\d+|\*),\s*(\d+|\*)\]"></pattern>
		</restriction>
	</simpleType>


	<simpleType name="dataTypeType">
		<restriction base="string">
			<enumeration value="INT" />
			<enumeration value="SINT" />
			<enumeration value="LINT" />
			<enumeration value="DINT" />
			<enumeration value="UINT" />
			<enumeration value="UDINT" />
			<enumeration value="ULINT" />
			<enumeration value="USINT" />
			<enumeration value="BOOLEAN" />
			<enumeration value="BYTE" />
			<enumeration value="WORD" />
			<enumeration value="DWORD" />
		</restriction>
	</simpleType>

	<!-- <simpleType name="cellType"> <restriction base="string"></restriction> 
		</simpleType> <simpleType name="cellSimpleValueType"> <restriction base="tns:cellType"></restriction> 
		</simpleType> <simpleType name="cellDontCareType"> <restriction base="tns:cellType"></restriction> 
		</simpleType> <simpleType name="cellRelationType"> <restriction base="tns:cellType"></restriction> 
		</simpleType> <simpleType name="cellExpressionType"> <restriction base="tns:cellType"></restriction> 
		</simpleType> -->

</schema>

=== Ron-ZL/verifaps-lib/examples/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<extended-test-table xmlns="http://formal.iti.kit.edu/exteta-1.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://formal.iti.kit.edu/exteta-1.0 ../src/xsd/exteta-1.0.xsd "
	version="">

	<variables>
		<variable data-type="INT" io="input" name="sensor" />
		<variable data-type="BOOLEAN" io="output" name="actuator" />
	</variables>

	<steps>
		<step duration="1">
			<cell>1</cell>
			<cell>true</cell>
		</step>

		<step duration="[1,5]">
			<cell>1</cell>
			<cell>sensor*2</cell>
		</step>

		<step duration="~">
			<cell>=prev(actuator)</cell>
			<cell>&gt;2</cell>
		</step>
	</steps>


</extended-test-table>
